package com.nexusflow.task;

public enum TaskType {
    REPOSITORY_SYNC,
    CODE_ANALYSIS,
    AI_ANALYSIS,
    METRICS_COLLECTION,
    RESUME_GITHUB_VERIFICATION,
    CROSS_PLATFORM_VERIFICATION,
    JOB_ANALYSIS,
    JOB_READINESS_ANALYSIS,
    COMPANY_PREPARATION,
    CUSTOM
}
